name: ${name}
main: ${main}

author: Arasple
contributors:
  - Bkm016

api-version: 1.13
version: ${version}

lib-version: ${libVersion}
lib-download: ${libDownload}
loader-version: ${loaderVersion}

github: https://github.com/Arasple/${name}
description: Modern & Advanced Menu-Plugin for Minecraft Servers
license: https://github.com/TrMenu/TrMenu/blob/v2/LICENSE.md

softdepend:
  - PlaceholderAPI
  - Vault
  - PlayerPoints
  - HeadDatabase
  - Oraxen
  - SkinsRestorer
  - ItemsAdder
  - floodgate-bukkit
  - FastScript
  - OptEco

built-time: ${built}
built-by: ${builder}
built-os: ${os}
