name: TrMenu Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  releaseJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

#      - name: Build with Gradle
#        run: ./gradlew clean build -s

      # First build
      - name: build
        id: build_1
        run: ./gradlew build
      # Second build
      - name: build (retry 1)
        id: build_2
        if: steps.build_1.outcome == 'failure'
        run: ./gradlew build
       # Third build
      - name: build (retry 2)
        id: build_3
        if: steps.build_2.outcome == 'failure'
        run: ./gradlew build
       # Fourth build
      - name: build (retry 3)
        id: build_4
        if: steps.build_3.outcome == 'failure'
        run: ./gradlew build
        # output jar
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: TrMenu Release
          path: build/libs/*.jar